### ISSUE TITLE
gret v1.4.0 not working on mac

### ISSUE THREAD

**Issue by aaethern** [greisane/gret#22]
whenever i try to turn on the addon it just gives me this error (im on blender 4.1.1)

<img width="1140" alt="Screenshot 2024-06-30 at 10 29 16 AM" src="https://github.com/greisane/gret/assets/110093342/fe902d78-ff0d-4b7c-b1db-ce10000ac5d6">

is there any fix or does gret only work on windows?

**Comment by greisane** [comment]
Could you post whatever gets printed to console?

![image](https://github.com/greisane/gret/assets/59247540/df3cec5a-2fb2-43ad-ba7d-cdeaac48cea0)

**Comment by aaethern** [comment]
i dont have that option

<img width="264" alt="Screenshot 2024-06-30 at 8 11 58 PM" src="https://github.com/greisane/gret/assets/110093342/b2b411a3-0f22-4ab3-bfda-9eb155471ba7">

**Comment by aaethern** [comment]
wait i think i got it

`Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/__init__.py", line 22, in <module>
    from . import importldraw
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/importldraw.py", line 38, in <module>
    from .loadldraw import loadldraw
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/loadldraw/loadldraw.py", line 1711, in <module>
    class BlenderMaterials:
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/loadldraw/loadldraw.py", line 1715, in BlenderMaterials
    __hasPrincipledShader = "ShaderNodeBsdfPrincipled" in [node.nodetype for node in getattr(bpy.types, "NODE_MT_category_SH_NEW_SHADER").category.items(None)]
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_SHADER'
WARN (bgl): source/blender/python/generic/bgl.cc:2678 BPyInit_bgl: 'bgl' imported without an OpenGL backend. Please update your add-ons to use the 'gpu' module.
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/__init__.py", line 47, in <module>
    from . import quad_swords
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/quad_swords.py", line 37, in <module>
    from . import gui
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/gui.py", line 22, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'
Reloading external rigs...
Reloading external metarigs...
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/TexTools-Blender-master/__init__.py", line 128, in <module>
    from . import op_texel_density_set
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/TexTools-Blender-master/op_texel_density_set.py", line 3, in <module>
    from bpy.types import FaceMap
ImportError: cannot import name 'FaceMap' from 'bpy.types' (unknown location)
register_class(...):
Warning: 'PT_ShapekeyTransfer' does not contain '_PT_' with prefix and suffix
Warning: addon-module object_print3d_utils found module but without '__addon_enabled__' field, possible name collision from file: '/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/addons/object_print3d_utils/__init__.py'
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/TexTools-Blender-master/__init__.py", line 128, in <module>
    from . import op_texel_density_set
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/TexTools-Blender-master/op_texel_density_set.py", line 3, in <module>
    from bpy.types import FaceMap
ImportError: cannot import name 'FaceMap' from 'bpy.types' (unknown location)
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/__init__.py", line 22, in <module>
    from . import importldraw
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/importldraw.py", line 38, in <module>
    from .loadldraw import loadldraw
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/loadldraw/loadldraw.py", line 1711, in <module>
    class BlenderMaterials:
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/io_scene_importldraw/loadldraw/loadldraw.py", line 1715, in BlenderMaterials
    __hasPrincipledShader = "ShaderNodeBsdfPrincipled" in [node.nodetype for node in getattr(bpy.types, "NODE_MT_category_SH_NEW_SHADER").category.items(None)]
                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'module' object has no attribute 'NODE_MT_category_SH_NEW_SHADER'
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/__init__.py", line 47, in <module>
    from . import quad_swords
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/quad_swords.py", line 37, in <module>
    from . import gui
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/kushiro_tools/gui.py", line 22, in <module>
    shader = gpu.shader.from_builtin('3D_UNIFORM_COLOR')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: expected a string in ('FLAT_COLOR', 'IMAGE', 'IMAGE_COLOR', 'SMOOTH_COLOR', 'UNIFORM_COLOR', 'POLYLINE_FLAT_COLOR', 'POLYLINE_SMOOTH_COLOR', 'POLYLINE_UNIFORM_COLOR'), got '3D_UNIFORM_COLOR'
blenderkit INFO: Global dir permissions are OK. [09:45:12.725, utils.py:1295]
blenderkit INFO: Skipping dependencies copy: bundled for python 3.10, running on python 3.11.6 (main, Jan  2 2024, 14:58:43) [Clang 15.0.0 (clang-1500.1.0.2.5)] [09:45:12.726, dependencies.py:23]
blenderkit INFO: Dependencies are available [09:45:12.726, dependencies.py:111]
blenderkit WARNING: Request for daemon reports failed: <class 'requests.exceptions.ConnectionError'> HTTPConnectionPool(host='127.0.0.1', port=62485): Max retries exceeded with url: /report (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1887b7c10>: Failed to establish a new connection: [Errno 61] Connection refused')) [09:45:13.167, timer.py:36]
blenderkit INFO: Daemon server starting on address http://127.0.0.1:62485, log file for errors located at: /Users/USER/blenderkit_data/daemon/daemon-62485.log [09:45:13.247, daemon_lib.py:605]
blenderkit INFO: Daemon is running on port 62485! [09:45:14.332, timer.py:86]
Read blend: "/Users/USER/Desktop/blend/izutsumi1.blend"
Traceback (most recent call last):
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/scripts/modules/addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/gret-master/__init__.py", line 77, in <module>
    modules = import_or_reload_modules(module_names, __name__)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/gret-master/__init__.py", line 37, in import_or_reload_modules
    module = globals()[module_name] = importlib.import_module(module_name)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/Library/Application Support/Steam/steamapps/common/Blender/Blender.app/Contents/Resources/4.1/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/USER/Library/Application Support/Blender/4.1/scripts/addons/gret-master/drawing.py", line 12, in <module>
    shader_image_alpha = gpu.types.GPUShader("""
                         ^^^^^^^^^^^^^^^^^^^^^^^
Exception: Shader Compile Error, see console for more details`

**Comment by aaethern** [comment]
is it fixable?

**Comment by greisane** [comment]
The console dump unfortunately tells me nothing, it's all just errors and warnings from other addons.
Though looking around I found a fork of gret with an apparent fix.

I'm including it in master branch now, could you pull and see if it works?

**Comment by aaethern** [comment]
it just gives me the same looking error again :(
<img width="1136" alt="Screenshot 2024-07-02 at 3 25 56 PM" src="https://github.com/greisane/gret/assets/110093342/555b70f4-7276-4408-8206-76ccc3e5d57f">

**Comment by greisane** [comment]
It's the same error because it's the same code. Either you didn't check out the changes or you didn't restart Blender.

1. Delete gret-master addon folder.
2. Get https://github.com/greisane/gret/archive/refs/heads/master.zip
3. Unzip to gret-master.
4. Restart Blender.

**Comment by aaethern** [comment]
oh right, yeah, thank you it worked! :D

**Comment by greisane** [comment]
Glad to hear that! Let me know if there are other Mac issues.
