### ISSUE TITLE
Can't enable the addon.

### ISSUE THREAD

**Issue by Electrognome** [greisane/gret#7]
When I try to enable GRET 0.3.0 by clicking a checkbox in addons tab, blender won't let me do it and prints this error log - 

Traceback (most recent call last):
  File "blender-3.1.2-windows-x64\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\__init__.py", line 52, in <module>
    modules = import_or_reload_modules(module_names, __name__)
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\__init__.py", line 31, in import_or_reload_modules
    module = globals()[module_name] = importlib.import_module(module_name)
  File "blender-3.1.2-windows-x64\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\mesh\__init__.py", line 23, in <module>
    modules = import_or_reload_modules(module_names, __name__)
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\__init__.py", line 31, in import_or_reload_modules
    module = globals()[module_name] = importlib.import_module(module_name)
  File "blender-3.1.2-windows-x64\3.1\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\mesh\shape_key_store.py", line 152, in <module>
    class ShapeKeyPanelPatcher(PanelPatcher):
  File "AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\gret-0_3_0\mesh\shape_key_store.py", line 154, in ShapeKeyPanelPatcher
    panel_type = bpy.types.DATA_PT_shape_keys
AttributeError: 'module' object has no attribute 'DATA_PT_shape_keys'

I am installing it on Blender 3.1.2, tried 3.1.0 but it prints the same exact error. 
0.2.0 GRET works just fine.

**Comment by greisane** [comment]
That's pretty weird, you're missing the shape key panel for some reason. Now it should enable, though some gret functions might not be available in your case.

**Comment by Electrognome** [comment]
> That's pretty weird, you're missing the shape key panel for some reason. Now it should enable, though some gret functions might not be available in your case.

Thanks for the swift fix, I appreciate it. Since you pointed out that it might be my personal issue I started digging around and found out that this addon is causing this issue for me because I hid my default shapekeys tab with settings from it. - https://github.com/MichaelGlenMontague/shape_keys_plus

Sorry for wasting your time with a false issue. And also thanks for the great addon, it's a lifesaver for me.

**Comment by greisane** [comment]
> > That's pretty weird, you're missing the shape key panel for some reason. Now it should enable, though some gret functions might not be available in your case.
> 
> Thanks for the swift fix, I appreciate it. Since you pointed out that it might be my personal issue I started digging around and found out that this addon is causing this issue for me because I hid my default shapekeys tab with settings from it. - https://github.com/MichaelGlenMontague/shape_keys_plus
> 
> Sorry for wasting your time with a false issue. And also thanks for the great addon, it's a lifesaver for me.

No problem!  This addon also looks pretty cool, I use shape keys a ton. Though I can't say I agree with it deleting the panel type, there's cleaner ways to hijack the user interface.

**Comment by CynroDrake** [comment]
I know this was closed, but i'm having a similar issue but i do have shape keys? let me copy paste some things, i'm getting out of luck in trying to find a solution myself
![image](https://github.com/greisane/gret/assets/58121060/0fc5816e-ecf2-4a7b-a1e2-29a7d0cea8d8)
![image](https://github.com/greisane/gret/assets/58121060/a48db386-8c20-41eb-839a-a5aa6c01ea6e)

I don't know what i'm doing wrong tbh

**Comment by CynroDrake** [comment]
Ooh I'll try that when I'm back home ty!
